// Copyright (c) 2012-2022 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <bitcoin-build-config.h> // IWYU pragma: keep

#include <clientversion.h>
#include <util/string.h>
#include <util/translation.h>

#include <tinyformat.h>

#include <string>
#include <vector>

using util::Join;

/**
 * Name of client reported in the 'version' message. Report the same name
 * for both bitcoind and bitcoin-qt, to make it harder for attackers to
 * target servers or GUI users specifically.
 */
const std::string UA_NAME("Satoshi");


#include <bitcoin-build-info.h>
// The <bitcoin-build-info.h>, which is generated by the build environment (cmake/script/GenerateBuildInfo.cmake),
// could contain only one line of the following:
//   - "#define BUILD_GIT_TAG ...", if the top commit is tagged
//   - "#define BUILD_GIT_COMMIT ...", if the top commit is not tagged
//   - "// No build information available", if proper git information is not available

//! git will put "#define GIT_COMMIT_ID ..." on the next line inside archives. $Format:%n#define GIT_COMMIT_ID "%H"$

#ifdef BUILD_GIT_TAG
    #define BUILD_DESC BUILD_GIT_TAG
    #define BUILD_SUFFIX ""
#else
    #define BUILD_DESC "v" CLIENT_VERSION_STRING
    #if CLIENT_VERSION_IS_RELEASE
        #define BUILD_SUFFIX ""
    #elif defined(BUILD_GIT_COMMIT)
        #define BUILD_SUFFIX "-" BUILD_GIT_COMMIT
    #elif defined(GIT_COMMIT_ID)
        #define BUILD_SUFFIX "-g" GIT_COMMIT_ID
    #else
        #define BUILD_SUFFIX "-unk"
    #endif
#endif

static const std::string CLIENT_BUILD(BUILD_DESC BUILD_SUFFIX);

std::string FormatFullVersion()
{
    return CLIENT_BUILD;
}

std::string FormatUpstreamVersionInfo()
{
    return strprintf("Based on Bitcoin Knots %d.%d.%d\nBitcoin Core consensus baseline %d.%d\n",
                     UPSTREAM_KNOTS_VERSION_MAJOR,
                     UPSTREAM_KNOTS_VERSION_MINOR,
                     UPSTREAM_KNOTS_VERSION_BUILD,
                     UPSTREAM_CORE_CONSENSUS_MAJOR,
                     UPSTREAM_CORE_CONSENSUS_MINOR);
}

/**
 * Format the subversion field according to BIP 14 spec (https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki)
 */
std::string FormatSubVersion(const std::string& name, int /*nClientVersion*/, const std::vector<std::string>& comments, const bool base_name_only)
{
    std::string comments_str;
    if (!comments.empty()) comments_str = strprintf("(%s)", Join(comments, "; "));
    const std::string satoshi_version = strprintf("%d.%d", UPSTREAM_CORE_CONSENSUS_MAJOR, UPSTREAM_CORE_CONSENSUS_MINOR);
    std::string ua = strprintf("/%s:%s%s/", name, satoshi_version, comments_str);
    if (!base_name_only) {
        const std::string purity_version = strprintf("%d.%d.%d", CLIENT_VERSION_MAJOR, CLIENT_VERSION_MINOR, CLIENT_VERSION_BUILD);
        ua += strprintf("Purity:%s/", purity_version);
    }
    return ua;
}

std::string CopyrightHolders(const bool symbol_only)
{
    const auto format_prefix = [&](int start_year) {
        if (symbol_only) {
            return strprintf("\xc2\xa9 %i-%i ", start_year, COPYRIGHT_YEAR);
        }
        return strprintf(_("Copyright (C) %i-%i "), start_year, COPYRIGHT_YEAR).translated;
    };

    std::string result = format_prefix(2026) + "The Bitcoin Purity developers";
    result += "\n" + format_prefix(2009) + "The Bitcoin Knots developers";
    result += "\n" + format_prefix(2009) + "The Bitcoin Core developers";
    return result;
}

std::string LicenseInfo()
{
    const std::string URL_SOURCE_CODE = "<https://github.com/saltduck/bitcoinpurity>";

    return CopyrightHolders(/*symbol_only=*/false) + "\n" +
           "\n" +
           strprintf(_("Please contribute if you find %s useful. "
                       "Visit %s for further information about the software."),
                     CLIENT_NAME, "<" CLIENT_URL ">")
               .translated +
           "\n" +
           strprintf(_("The source code is available from %s."), URL_SOURCE_CODE).translated +
           "\n" +
           "\n" +
           _("This is experimental software.") + "\n" +
           strprintf(_("Distributed under the MIT software license, see the accompanying file %s or %s"), "COPYING", "<https://opensource.org/licenses/MIT>").translated +
           "\n";
}

int64_t g_software_expiry{DEFAULT_SOFTWARE_EXPIRY};

bool IsThisSoftwareExpired(int64_t nTime)
{
    if (g_software_expiry <= 0) {
        return false;
    }
    return (nTime > g_software_expiry);
}
